"""filed datatype change

Revision ID: eb709bf35533
Revises: 1bf35cacc0aa
Create Date: 2024-12-06 15:40:54.222213

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb709bf35533'
down_revision: Union[str, None] = '1bf35cacc0aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('profiles', 'bio',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('profiles', 'bio',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
